name-template: 'v$RESOLVED_VERSION-fork ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION-fork'
categories:
  - title: 'âš ï¸ Breaking changes'
    labels:
      - 'breaking change'
      - 'breaking '
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ“ƒ Documents'
    labels:
      - 'docs'
  - title: 'ğŸ§© Dependency Updates'
    labels:
      - 'deps'
      - 'dependencies'
      - 'bump'
    collapse-after: 5
  - title: 'ğŸ§° Maintenance'
    label: 'chore'
  - title: 'ğŸ”¬ Others'
    labels:
      - 'style'
      - 'refactor'
      - 'test'
      - 'ci'
    collapse-after: 5
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES